//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarberShop1.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BarberShopEntities : DbContext
    {
        public BarberShopEntities()
            : base("name=BarberShopEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EmployeeTable> EmployeeTable { get; set; }
        public virtual DbSet<HaircutTable> HaircutTable { get; set; }
        public virtual DbSet<ImageEmployeeTable> ImageEmployeeTable { get; set; }
        public virtual DbSet<PaulTable> PaulTable { get; set; }
        public virtual DbSet<PostTable> PostTable { get; set; }
        public virtual DbSet<RecordTable> RecordTable { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
