//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarberShop1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecordTable
    {
        public int PesonalNumberRecord { get; set; }
        public int PNEmployeeRecord { get; set; }
        public int PNHaircutRecord { get; set; }
        public System.DateTime DateRecord { get; set; }
        public System.TimeSpan TimeRecord { get; set; }
        public string SurnameClient { get; set; }
        public string NameClient { get; set; }
    
        public virtual EmployeeTable EmployeeTable { get; set; }
        public virtual HaircutTable HaircutTable { get; set; }
    }
}
